/*
 * This source file was generated by the Gradle 'init' task
 */
package com.tech.basic;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class DbExampleTest {
    @Test
    void main_runs_without_exception() {
        assertDoesNotThrow(() -> DbExample.main(new String[]{}));
    }
}
